### ISSUE TITLE
Addition of a block to the Palette - Operators

### ISSUE THREAD

**Issue by DeepaMuralidhar** [PencilCode/pencilcode#180]
![image](https://cloud.githubusercontent.com/assets/13576456/9038917/f8b0d9dc-39c5-11e5-914c-c9b5f45bff52.png)

**Comment by davidbau** [comment]
Hi Deepa - what's being shown here - was this issue accidentally created?

**Comment by DeepaMuralidhar** [comment]
Sorry for my initial brevity. So this block which lets multiple programming statements in one statement is useful when a programmer is creating variables. I recommend that the block be available under operators for drag and drop use.

**Comment by davidbau** [comment]
Is it still important in coffeescript where variables are created automatically on first use?  Unlike Javascript and Java (but like python), you do not need "var x, y;" or "int x, y;" declarations before use.

We could add a semicolon operator `__ ; __` that allows chains of commands to be sequenced, but it just combines two things....

I guess my feeling is that we're best off just having students drag multiple blocks in to sequence them vertically in a line rather than providing a horizontal combiner block.

**Comment by DeepaMuralidhar** [comment]
You know, I really agree with you. I prefer to have students write one block below another. The only reason I thought this may be necessary is when I saw the code for "star" and tried to understand and look for the block. I am good with closing this issue and paying close attention to making all programming statements be one on each line for all the text based code as well as block based code. (Maybe even make it a programming style suggestion)

**Comment by davidbau** [comment]
Yes.  The reason that there are so many semicolons in the book is to make
the book compact.

I think when we create or copy the examples for the classroom material, we
shouldn't use semicolons.

**Comment by DeepaMuralidhar** [comment]
Perfect. And also have a style guide where we recommend best practices.
