### ISSUE TITLE
console.log and alert executions are happening at the beginning of the program execution

### ISSUE THREAD

**Issue by Dinuka2013513** [PencilCode/pencilcode#197]
When there are console.log and alert in the program, all of them are executed at the beginning of the program execution. This seems like an issue in pencil-tracer

**Comment by Dinuka2013513** [comment]
Here is an example http://dinuka.pencilcode.net/edit/console_alert_bug

**Comment by davidbau** [comment]
This issue is unrelated to pencil tracer.

It is a fundamental issue with the way the turtle library works.  Since javascript is a nonblocking environment, you cannot write code where `fd(100)` takes one second and "blocks" the program until the next line of code.  Instead, you must queue animations to be executed later.

This is how jQuery and all animation libraries in Javascript work.  The result is that all queued actions run slowly and in the future, but unqueued actions such as console.log occur right away.

I can imagine a total resdeign that takes a different approach to this problem, but it's not a small bug.

**Comment by davidbau** [comment]
This is not a bug, but a design choice.  See:

https://groups.google.com/forum/#!searchin/pencilcode/animation$20order/pencilcode/idx8JB6Oxls/37jqJhzGDS4J
as well as
http://ref.pencilcode.net/turtle/speed.html

**Comment by xinan** [comment]
Is there any way to work around it easily?

**Comment by davidbau** [comment]
Use "await turtle.done defer()" in front of the parts of the code that you
want to block to wait until after the turtle is finished moving.
